### ISSUE TITLE
Help needed

### ISSUE THREAD

**Issue by Escarter** [imajkumar/laravel-binary-tree#1]
Hello, thanks a lot for this package!. Please, do you have documentation on how to use this package?

**Comment by imajkumar** [comment]
Yes!! provide you soon

**Comment by imajkumar** [comment]
add this in composer.json
"imajkumar/laravel-binary-tree": "dev-master",

composer install
add only
'Ayra\Providers\AyraServiceProvider',
in config/app.php 's provide
add follow readme document
