### ISSUE TITLE
How to Install this on laravel 5.8

### ISSUE THREAD

**Issue by jayGorio** [imajkumar/laravel-binary-tree#2]
I already installed your package. Also I added "Ayra\Providers\AyraServiceProvider::class," on config.app.php. But when I run php artisan ayra:install User I get this error "Method Ayra\Console\InstallCommand::handle() does not exist"

**Comment by imajkumar** [comment]
add this in composer.json 
"imajkumar/laravel-binary-tree": "dev-master",

composer install
add only
'Ayra\Providers\AyraServiceProvider',
 in config/app.php 's provide
