### ISSUE TITLE
How can I create model?

### ISSUE THREAD

**Issue by hurano** [imajkumar/laravel-binary-tree#4]
@imajkumar imajkumar
I already installed. I would like to know how I can create this model to use for category table.

Thanks.

**Comment by imajkumar** [comment]
Yes ,
Create a file category.php
and this code in it  only 
`<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Arya\Node;

class Category extends \Ayra\Node
{

}`

and you can create root by 
` $root = Category::create(['name' => 'Root','user_id'=>1]);`
I hope above explanation will help you
Thanks
